# Generated by Django 4.1.1 on 2022-11-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('current', models.DecimalField(decimal_places=9, max_digits=18)),
                ('voltage', models.DecimalField(decimal_places=9, max_digits=18)),
                ('power', models.DecimalField(decimal_places=9, max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('unit', models.CharField(max_length=24)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('current', models.DecimalField(decimal_places=9, max_digits=18)),
                ('voltage', models.DecimalField(decimal_places=9, max_digits=18)),
                ('power', models.DecimalField(decimal_places=9, max_digits=18)),
                ('description', models.TextField(blank=True, default='')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
