# Generated by Django 4.1.1 on 2022-11-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('lightning', 'Lightning'), ('electronics', 'Electronics'), ('appliances', 'Appliances'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
