# Generated by Django 4.1.1 on 2022-11-13 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('classroom', 'Classroom'), ('amenities', 'Amenities'), ('outdoors', 'Outdoors'), ('other', 'Other')], default='other', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='measurement',
            name='value',
            field=models.DecimalField(decimal_places=9, max_digits=18),
        ),
    ]
