# Generated by Django 4.1.1 on 2022-11-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_device_room_sensor_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='type',
            field=models.CharField(choices=[('light', 'Light'), ('temperature', 'Temperature'), ('humidity', 'Humidity'), ('voltage', 'Voltage'), ('current', 'Current'), ('other', 'Other')], default='other', max_length=100),
        ),
    ]
