# Generated by Django 4.1.1 on 2022-11-13 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sensor_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='current',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='power',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='voltage',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=18, null=True),
        ),
    ]
